name: Dual Repository Publish

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:
    inputs:
      publish_to_org:
        description: 'Publish to organization repository'
        required: false
        default: 'false'
        type: boolean
      create_release:
        description: 'Create GitHub release'
        required: false
        default: 'false'
        type: boolean

env:
  NODE_VERSION: '20'
  BUN_VERSION: 'latest'

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: bun install

      - name: Run linting
        run: bun run lint

      - name: Run tests
        run: bun run test

      - name: Build main application
        run: bun run build

      - name: Build documentation site
        run: |
          cd docs-site
          bun install
          bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            .next/
            docs-site/build/
          retention-days: 1

  publish-main:
    name: Publish to Main Repository
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'

  publish-organization:
    name: Publish to Organization Repository
    runs-on: ubuntu-latest
    needs: test
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/master') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_to_org == 'true')
    
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: main-repo

      - name: Checkout organization repository
        uses: actions/checkout@v4
        with:
          repository: FormerlyIncarcerated/org
          token: ${{ secrets.ORG_REPO_TOKEN }}
          path: org-repo

      - name: Sync files to organization repository
        run: |
          # Copy essential files to organization repository
          cp main-repo/README.md org-repo/
          cp main-repo/LICENSE org-repo/
          cp main-repo/package.json org-repo/
          cp main-repo/.gitignore org-repo/
          
          # Copy documentation
          cp -r main-repo/docs/ org-repo/docs/
          
          # Copy GitHub configuration
          cp -r main-repo/.github/ org-repo/.github/
          
          # Copy profile directory if it exists
          if [ -d "main-repo/profile" ]; then
            cp -r main-repo/profile/ org-repo/profile/
          fi

      - name: Commit and push to organization repository
        run: |
          cd org-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add .
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "sync: Update from main repository ($(date))"
            git push
          fi

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [test, publish-main]
    if: |
      github.event_name == 'push' && 
      startsWith(github.ref, 'refs/tags/v') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.create_release == 'true')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "version=v$(date +%Y.%m.%d)" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body: |
            ## What's Changed
            
            This release includes the latest updates to the FormerlyIncarcerated.org platform.
            
            ### Features
            - Latest platform improvements
            - Documentation updates
            - Performance optimizations
            
            ### Technical Details
            - Built with Next.js 15 and React 19
            - Comprehensive test coverage
            - Production-ready deployment
            
            **Full Changelog**: https://github.com/${{ github.repository }}/compare/v1.1.0...${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
